services:
  # Backend API Service
  - type: web
    name: playbooks-api
    runtime: python
    buildCommand: cd website/api && pip install -r requirements.prod.txt
    startCommand: cd website/api && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0

  # Frontend Static Site
  - type: web
    name: playbooks-frontend
    runtime: node
    buildCommand: cd website/frontend && npm install && npm run build
    startCommand: cd website/frontend && npm start
    envVars:
      - key: NODE_VERSION
        value: 23.x
      - key: API_URL
        value: https://playbooks-api.onrender.com
      - key: NEXT_PUBLIC_API_URL
        value: https://playbooks-api.onrender.com
