[tool.poetry]
name = "playbooks"
version = "0.1.0"
license = "LICENSE-CODE"
description = "A framework for creating AI agents using human-readable playbooks"
authors = ["Amol Kelkar <kelkar.amol@gmail.com>"]
readme = "README.md"
packages = [{include = "playbooks", from = "src"}]

[tool.poetry.dependencies]
python = "^3.10"
openai = "*"
anthropic = "*"
google_cloud_aiplatform = "*"
typer = "*"
rich = "*"
python_dotenv = "*"
litellm = "*"
md2py = "*"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
pytest_cov = "^4.1.0"
black = "^23.7.0"
ruff = "*"
pyright = "*"
pytest_asyncio = "*"
autogen_core = "^0.4.0.dev13"
mypy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.ruff]
select = ["E", "F", "B"]
ignore = ["B006", "B018", "E501"]
line-length = 88

[tool.poetry.scripts]
playbooks = "playbooks.cli.cli:main"